dubbo:
  application:
    id: quickstart
    name: quickstart
  scan:
    base-packages: com.dubbotry.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${serverip}:8848