spring:
  application:
    name: feign-client

ribbon-server:
  ribbon:
    listOfServers: localhost:8080,localhost:8082

server:
  port: 7070

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  compression:
    request:
      enabled: true