spring:
  application:
    name: spring-cloud-dubbo-demo-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${serverip}:8848 # 注册中心地址

dubbo:
  scan:
    base-packages: com.demo.springcloud.dubbo.provider.service # dubbo服务扫描基础包路径
  protocol:
    id: dubbo # dubbo服务暴露的协议配置
    name: dubbo # 协议名称
    port: 20882 # 协议端口，-1表示自增端口，从20880开始
  # Dubbo服务注册中心配置，其中子属性 address 的值 "spring-cloud://localhost"，说明挂载到 Spring Cloud 注册中心
  # registry:

